Custom scan next
WatWowMap/ReactMap pull request #655
Opened 2023-02-06 13:06 UTC by lenisko

2023-02-06 21:15 UTC, TurtIeSocks requested changes
Overall looks good, thanks for the pr!

2023-02-06 21:15 UTC, TurtIeSocks commented on src/components/layout/FloatingBtn.jsx
> +      scannerType === 'rdm' || scannerType === 'custom' ? (
```suggestion
      scannerType !== 'mad'  ? (
```

2023-02-06 21:15 UTC, TurtIeSocks commented on src/components/layout/dialogs/scanner/ScanNextTarget.jsx
> +            {scannerType === 'rdm' || scannerType === 'custom' && (
```suggestion
            {scannerType !== 'mad' && (
```

2023-02-06 21:15 UTC, TurtIeSocks commented on src/components/layout/dialogs/scanner/ScanZoneTarget.jsx
> +            {scannerType === 'rdm' || scannerType === 'custom' && (
```suggestion
            {scannerType !== 'mad' && (
```

2023-02-07 04:31 UTC, TurtIeSocks approved these changes

2023-02-07 04:31 UTC, merged

2023-02-07 22:29 UTC, kamieniarz commented
Looks like this PR broke discord messages

2023-02-07 23:08 UTC, lenisko commented
@kamieniarz Unless you made some changes to `default.json` it shouldn't. Any errors?

2023-02-07 23:12 UTC, kamieniarz commented
I changed nothing, nothing in logs too. Revert helped

2023-02-07 23:28 UTC, lenisko commented
Tested by two all works. Make sure you haven't blocked changes to `default.json` or make sure you have this https://github.com/WatWowMap/ReactMap/blob/develop/server/src/configs/default.json#L565

2023-02-08 14:42 UTC, ReuschelCGN commented
> Looks like this PR broke discord messages

Sorry but here too!