Tweaking of local strategy
WatWowMap/ReactMap pull request #714
Opened 2023-06-01 21:01 UTC by Petap0w

This PR tweaks slightly the local strategy as follows:
- linking a local user to an existing Discord registered account who has gym Badges will import them on the new consolidated account
- linking a local user to an existing Discord registered account who has filled in some custom Data fields will import them on the consolidated account
- Trial Period can also be used with local strategy with copying the example into a `"strategyConfig"` object in the `local` strategy block
- Custom local roles can be used to grant different perms to users authenticating via the local strategy if it is stored in the `data` field with the database prop `status`:
```
      "extraUserFields": [
        {
          "name": "Status",
          "database": "status",
        },...
```
- `data` extraUserFields can have a `disabled` attribute so they show on the profile page but can't be edited by the user. Useful to have an external service showing some user attributes

Why all this?
So you can manage with an external service that is not Discord the user access to the map for people who are Discord disabled and want just a username / login:
```
      "extraUserFields": [
        {
          "name": "Status",
          "database": "status",
          "disabled": true
        },
        {
          "name": "End Date",
          "database": "premium_expiry",
          "disabled": true
        },
        {
          "name": "Paypal account",
          "database": "paypal"
        }
      ]
```
![profile](https://github.com/WatWowMap/ReactMap/assets/47784174/fbf65cb2-354a-4ce0-a1aa-8ed5d0fd5e20)

Then having some perms with `"Donor"` just like you would use a Discord role will give them to this user.

2023-06-02 04:03 UTC, TurtIeSocks requested changes
Exciting that the local strategy will be a bit more useful!

Feedback is mostly concerning an issue with MariaDB returning a string for JSON columns while MySQL returns an actual JSON. I will try to give this PR a try tomorrow to clear up some other possible styling feedback. Thanks!

2023-06-02 04:03 UTC, TurtIeSocks commented on src/components/layout/custom/Generator.jsx
> +              style={subBlock.style || { textAlign: 'center' }}
Hmm I'm not sure about this one. I think this might be a breaking change, I thought the `.style` prop customize the component inside of the Grid?

2023-06-02 04:03 UTC, TurtIeSocks commented on src/hooks/useConfig.js
> +        data: serverSettings.user?.data ? JSON.parse(serverSettings.user?.data) : {},
Same MariaDB issue here

2023-06-02 05:41 UTC, Petap0w commented on server/src/services/DiscordClient.js
> +              .where('data', null)
If the user updated some extraFields on his most recent account they shouldn’t be overwritten with old data

2023-06-02 05:43 UTC, Petap0w commented on src/components/layout/auth/Local.jsx
> -          <Grid item xs={12} sm={5} style={{ textAlign: 'center' }}>
With forcing size of fields inside the LocalLogin component there is no customization possible whereas leaving it free you can inline them or align them with the parent div

2023-06-03 19:39 UTC, TurtIeSocks approved these changes

2023-06-03 19:39 UTC, TurtIeSocks commented
Thanks!

2023-06-03 19:39 UTC, merged