Remove location accuracy circle overlay
WatWowMap/ReactMap pull request #92
Opened 2021-06-14 08:20 UTC by Petap0w

When sharing connection there is sometimes a large location accuracy circle overlay which makes the map content not really visible.

2021-06-14 17:27 UTC, TurtIeSocks requested changes
I don't think we should remove it entirely as this seems like a smaller use case than those who don't share mobile connections. I would suggest, at most, we reduce the opacity. 
```js
  const locateOptions = {
    keepCurrentZoomLevel: true,
    circleStyle: { fillOpacity: 0.05 },
    strings: {
      title: t('useMyLocation'),
    },
    onActivate: () => { },
  }
```
Alternatively, put it in Settings.

2021-06-14 17:32 UTC, lenisko commented
Settings ++

2021-06-14 21:04 UTC, lenisko commented
I think that client side switch would make more sense. Sorry for not pointing it before... @TurtIeSocks ?

2021-06-14 21:12 UTC, Petap0w commented
when you don't have gps issues you won't even have this circle, and when you have gps problems you'll want it off to see the map (and accuracy is not really an important information anyways when using the map, you'll just want the screen to be centered "around" your location when clicking on location button so you don't have to scroll).

2021-06-14 21:49 UTC, lenisko commented
For me it happens quite often that I lose a location on the map (thank you Android) so it's nice to have. Making it client side setting users would be able to decide whatever they need this or not at the current time. For starter maybe @TurtIeSocks solution to make it more transparent?

2021-06-16 21:51 UTC, TurtIeSocks commented on server/src/configs/default.json
> +    "enableFeedback": false,
I would remove this change from this PR since it's coming in your local auth PR anyway, just to reduce conflicts. After that, I can merge this in.

2021-06-17 14:40 UTC, closed without merging